### ISSUE TITLE
When parsing a SUMO .net.xml: NotImplementedError: Multi-part geometries do not provide a coordinate sequence

### ISSUE THREAD

**Issue by philippwulff** [patmalcolm91/SumoNetVis#32]
I would like use the `net.generate_obj_text()` function to create an .obj file from my .net.xml file.

From what I understand, it should be as simple as this:

```
import SumoNetVis

path = 'map_name.net.xml'
net = SumoNetVis.Net(path)

# Save a network as an OBJ file
with open('map_name.obj', "w") as f:
    f.write(net.generate_obj_text())
```

However, I receive this error:

```
Traceback (most recent call last):
  File "/home/marcel/Documents/Philipp/Prepare Map for CARLA/net_to_obj_script.py", line 9, in <module>
    f.write(net.generate_obj_text())
  File "/home/marcel/.local/lib/python3.6/site-packages/SumoNetVis/Net.py", line 993, in generate_obj_text
    objects += lane.get_markings_as_3d_objects()
  File "/home/marcel/.local/lib/python3.6/site-packages/SumoNetVis/Net.py", line 404, in get_markings_as_3d_objects
    for marking in self._guess_lane_markings():
  File "/home/marcel/.local/lib/python3.6/site-packages/SumoNetVis/Net.py", line 519, in _guess_lane_markings
    stop_line = LineString([end_left.coords[-1], end_right.coords[0]])
  File "/home/marcel/.local/lib/python3.6/site-packages/shapely/geometry/base.py", line 868, in coords
    "Multi-part geometries do not provide a coordinate sequence")
NotImplementedError: Multi-part geometries do not provide a coordinate sequence
```
Have you encountered this issue before and do you know how to resolve it?

**Comment by patmalcolm91** [comment]
Possibly resolved by 1fe7bec4899de4256def70cf72e16ebcea9789a3, but needs testing.

**Comment by philippwulff** [comment]
I did install the library from this updated version of the repo this time, but the error was not resolved.

```
Traceback (most recent call last):
  File "/home/marcel/Documents/Philipp/Prepare Map for CARLA/net_to_obj_script.py", line 9, in <module>
    f.write(net.generate_obj_text())
  File "/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py", line 996, in generate_obj_text
    objects += lane.get_markings_as_3d_objects()
  File "/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py", line 404, in get_markings_as_3d_objects
    for marking in self._guess_lane_markings():
  File "/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py", line 519, in _guess_lane_markings
    if not hasattr(end_left, "coords") or not hasattr(end_right, "coords"):
  File "/home/marcel/.local/lib/python3.6/site-packages/shapely/geometry/base.py", line 868, in coords
    "Multi-part geometries do not provide a coordinate sequence")
NotImplementedError: Multi-part geometries do not provide a coordinate sequence
```

Basically the same error. Some lines differ, because of your adjustments to the code.

**Comment by patmalcolm91** [comment]
Thanks for testing the change. Can you try it again with the most recent commit (1fe7bec4899de4256def70cf72e16ebcea9789a3)?

**Comment by philippwulff** [comment]
This throws a different error:

```
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:522: UserWarning: Can't generate stopline geometry for lane -118607504#7_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:522: UserWarning: Can't generate stopline geometry for lane -130185484#1_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
Traceback (most recent call last):
  File "/home/marcel/Documents/Philipp/Prepare Map for CARLA/net_to_obj_script.py", line 9, in <module>
    f.write(net.generate_obj_text())
  File "/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py", line 997, in generate_obj_text
    objects += lane.get_markings_as_3d_objects()
  File "/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py", line 404, in get_markings_as_3d_objects
    for marking in self._guess_lane_markings():
  File "/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py", line 520, in _guess_lane_markings
    stop_line = LineString([end_left.coords[-1], end_right.coords[0]])
IndexError: list index out of range
```

**Comment by patmalcolm91** [comment]
How about now, with the change in 9a5262f42064a5fe7c876bcf570b25ffe4ddb347?

**Comment by philippwulff** [comment]
```
/usr/bin/python3.6 "/home/marcel/Documents/Philipp/Prepare Map for CARLA/net_to_obj_script.py"
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:522: UserWarning: Can't generate stopline geometry for lane -118607504#7_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:522: UserWarning: Can't generate stopline geometry for lane -130185484#1_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:522: UserWarning: Can't generate stopline geometry for lane -138300627_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:522: UserWarning: Can't generate stopline geometry for lane -145069334_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:522: UserWarning: Can't generate stopline geometry for lane -202167799#3_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:522: UserWarning: Can't generate stopline geometry for lane -215826167#2_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:522: UserWarning: Can't generate stopline geometry for lane -23622140#0_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:522: UserWarning: Can't generate stopline geometry for lane -25148812_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:515: UserWarning: Unable to generate stop line for short lane -25149251#4_0
  warnings.warn("Unable to generate stop line for short lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:515: UserWarning: Unable to generate stop line for short lane -262722743_0
  warnings.warn("Unable to generate stop line for short lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:522: UserWarning: Can't generate stopline geometry for lane -26339462#0_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:522: UserWarning: Can't generate stopline geometry for lane -27830322#2_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:522: UserWarning: Can't generate stopline geometry for lane -30054346#0_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:522: UserWarning: Can't generate stopline geometry for lane -30054528#2_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:515: UserWarning: Unable to generate stop line for short lane -32008983_1
  warnings.warn("Unable to generate stop line for short lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:522: UserWarning: Can't generate stopline geometry for lane -32229976_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:522: UserWarning: Can't generate stopline geometry for lane -32395288#2_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:515: UserWarning: Unable to generate stop line for short lane -32530113#1_0
  warnings.warn("Unable to generate stop line for short lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:522: UserWarning: Can't generate stopline geometry for lane -35342848#0_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:522: UserWarning: Can't generate stopline geometry for lane -379723622#0_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:522: UserWarning: Can't generate stopline geometry for lane -433809229_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:522: UserWarning: Can't generate stopline geometry for lane -643314345_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
TopologyException: assigned depths do not match at 6408.5858586833974 6518.6886640037483
Traceback (most recent call last):
  File "/home/marcel/Documents/Philipp/Prepare Map for CARLA/net_to_obj_script.py", line 9, in <module>
    f.write(net.generate_obj_text())
  File "/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py", line 997, in generate_obj_text
    objects += lane.get_markings_as_3d_objects()
  File "/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py", line 404, in get_markings_as_3d_objects
    for marking in self._guess_lane_markings():
  File "/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py", line 517, in _guess_lane_markings
    end_left = end_cl.parallel_offset(self.width / 2, side="left")
  File "/home/marcel/.local/lib/python3.6/site-packages/shapely/geometry/linestring.py", line 146, in parallel_offset
    self, distance, resolution, join_style, mitre_limit, side))
  File "/home/marcel/.local/lib/python3.6/site-packages/shapely/geometry/base.py", line 78, in geom_factory
    raise ValueError("No Shapely geometry can be created from null value")
ValueError: No Shapely geometry can be created from null value

Process finished with exit code 1
```

**Comment by patmalcolm91** [comment]
How about now (68cdc211)?

**Comment by philippwulff** [comment]
Appears to be the same error:

```
/usr/bin/python3.6 "/home/marcel/Documents/Philipp/Prepare Map for CARLA/net_to_obj_script.py"
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:525: UserWarning: Can't generate stopline geometry for lane -118607504#7_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:525: UserWarning: Can't generate stopline geometry for lane -130185484#1_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:525: UserWarning: Can't generate stopline geometry for lane -138300627_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:525: UserWarning: Can't generate stopline geometry for lane -145069334_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:525: UserWarning: Can't generate stopline geometry for lane -202167799#3_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:525: UserWarning: Can't generate stopline geometry for lane -215826167#2_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:525: UserWarning: Can't generate stopline geometry for lane -23622140#0_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:525: UserWarning: Can't generate stopline geometry for lane -25148812_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:515: UserWarning: Unable to generate stop line for short lane -25149251#4_0
  warnings.warn("Unable to generate stop line for short lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:515: UserWarning: Unable to generate stop line for short lane -262722743_0
  warnings.warn("Unable to generate stop line for short lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:525: UserWarning: Can't generate stopline geometry for lane -26339462#0_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:525: UserWarning: Can't generate stopline geometry for lane -27830322#2_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:525: UserWarning: Can't generate stopline geometry for lane -30054346#0_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:525: UserWarning: Can't generate stopline geometry for lane -30054528#2_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:515: UserWarning: Unable to generate stop line for short lane -32008983_1
  warnings.warn("Unable to generate stop line for short lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:525: UserWarning: Can't generate stopline geometry for lane -32229976_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:525: UserWarning: Can't generate stopline geometry for lane -32395288#2_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:515: UserWarning: Unable to generate stop line for short lane -32530113#1_0
  warnings.warn("Unable to generate stop line for short lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:525: UserWarning: Can't generate stopline geometry for lane -35342848#0_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:525: UserWarning: Can't generate stopline geometry for lane -379723622#0_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:525: UserWarning: Can't generate stopline geometry for lane -433809229_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py:525: UserWarning: Can't generate stopline geometry for lane -643314345_0
  warnings.warn("Can't generate stopline geometry for lane " + self.id)
TopologyException: assigned depths do not match at 6408.5858586833974 6518.6886640037483
Traceback (most recent call last):
  File "/home/marcel/Documents/Philipp/Prepare Map for CARLA/net_to_obj_script.py", line 9, in <module>
    f.write(net.generate_obj_text())
  File "/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py", line 1000, in generate_obj_text
    objects += lane.get_markings_as_3d_objects()
  File "/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py", line 404, in get_markings_as_3d_objects
    for marking in self._guess_lane_markings():
  File "/home/marcel/Documents/Philipp/Prepare Map for CARLA/SumoNetVis/Net.py", line 520, in _guess_lane_markings
    end_left = end_cl.parallel_offset(self.width / 2, side="left")
  File "/home/marcel/.local/lib/python3.6/site-packages/shapely/geometry/linestring.py", line 146, in parallel_offset
    self, distance, resolution, join_style, mitre_limit, side))
  File "/home/marcel/.local/lib/python3.6/site-packages/shapely/geometry/base.py", line 78, in geom_factory
    raise ValueError("No Shapely geometry can be created from null value")
ValueError: No Shapely geometry can be created from null value

Process finished with exit code 1

```

**Comment by patmalcolm91** [comment]
Ok, strange. I implemented several additional checks in 2e98e95d. Does that make any difference?

**Comment by philippwulff** [comment]
This has fixed it! I still receive those UserWarning messages and am not quite sure what to think of them, but I got the output file. I will check if it is intact. Thanks!

**Comment by patmalcolm91** [comment]
Glad to hear that! You can safely ignore the UserWarning messages. The library just prints them out for the sake of transparency (so you know that certain objects were skipped/ignored in the export process).
